# Generated by Django 3.0.2 on 2020-01-06 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200106_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='under',
            options={'ordering': ('name',), 'verbose_name': 'under', 'verbose_name_plural': 'unders'},
        ),
        migrations.AlterField(
            model_name='under',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Unders', to='items.Category'),
        ),
    ]
