# Generated by Django 3.0.2 on 2020-01-28 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20200108_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='under',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='items.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/products'),
        ),
        migrations.DeleteModel(
            name='Under',
        ),
    ]
